excludeFiles:
  - ./**/*.html
extends:
  - markuplint:recommended
parser:
  .tsx?$: '@markuplint/jsx-parser'
specs:
  .tsx?$: '@markuplint/react-spec'
nodeRules:
  selector: img
  rules:
    required-attr: alt
